apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "brokerage-service-ui.fullname" . }}
  labels:
    app: {{ include "brokerage-service-ui.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      component: {{ .Values.componentName }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        component: {{ .Values.componentName }}
    spec:
      {{- with .Values.image.imagePullSecret }}
      imagePullSecrets:
        - name: {{ . | quote }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: brokerage-service-ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NEXT_PUBLIC_BROKERAGE_SERVICE_API
              value: {{ .Values.env.brokerageServiceApiUrl | quote }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
