{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-ingress"
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | quote }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ printf "/%s" (trimPrefix "/" (.Values.ingress.path | default "")) | quote }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: "{{ include "brokerage-service-ui.fullname" . }}-service"
                port:
                  number: {{ .Values.service.port }}
{{- end }}

